### PR TITLE
lets-icons: added missing ng-package files to expose the entrypoints

### PR DESCRIPTION
**Pull request by BoogieMonsta**
Added the `ng-package.json` files to each subset in Lets Icons, to expose the entrypoints

### CODE REVIEW

**Comment by BoogieMonsta** [comment]
Hey @ashley-hunter ! Just adding the `ng-package.json` files to each subset in Lets Icons, to expose the entrypoints. Without them, it seems impossible to import anything from Lets. Please correct me if I'm wrong, though! 🙂

**Comment by ashley-hunter** [comment]
Hey! Thank you, you are absolutely correct! Not sure how this happened as I used the Nx secondary entry point generator which should have created these 🤔 something obviously went wrong somewhere, but thank you for the fix. I'll get this merged and a new release created shortly, thanks again!

**Comment by ashley-hunter** [comment]
Release done! Should now work as expected!

**Comment by BoogieMonsta** [comment]
I can confirm it does work as expected, now! Thank you 🙂

**Pull request merged**
